// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t *ui_mainScreen;
void ui_event_onButton( lv_event_t * e);
extern lv_obj_t *ui_onButton;
extern lv_obj_t *ui_onButtonLabel;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_manualMode
void ui_manualMode_screen_init(void);
extern lv_obj_t *ui_manualMode;
void ui_event_StartButton( lv_event_t * e);
extern lv_obj_t *ui_StartButton;
extern lv_obj_t *ui_Label2;
void ui_event_BackButton( lv_event_t * e);
extern lv_obj_t *ui_BackButton;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_TimePanel;
void ui_event_HoursPlus( lv_event_t * e);
extern lv_obj_t *ui_HoursPlus;
extern lv_obj_t *ui_Label10;
void ui_event_HoursMinus( lv_event_t * e);
extern lv_obj_t *ui_HoursMinus;
extern lv_obj_t *ui_Label11;
void ui_event_MinutesPlus( lv_event_t * e);
extern lv_obj_t *ui_MinutesPlus;
extern lv_obj_t *ui_Label4;
void ui_event_MinutesMinus( lv_event_t * e);
extern lv_obj_t *ui_MinutesMinus;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_HoursLbl;
extern lv_obj_t *ui_MinutesLbl;
extern lv_obj_t *ui_Separator;
extern lv_obj_t *ui_TemperaturePanel;
extern lv_obj_t *ui_TemperatureLbl;
void ui_event_PlusTemperature( lv_event_t * e);
extern lv_obj_t *ui_PlusTemperature;
extern lv_obj_t *ui_Label5;
void ui_event_MinusTemperature( lv_event_t * e);
extern lv_obj_t *ui_MinusTemperature;
extern lv_obj_t *ui_Label8;
void ui_event_Fan( lv_event_t * e);
extern lv_obj_t *ui_Fan;
extern lv_obj_t *ui_Label9;
void ui_event_Grill( lv_event_t * e);
extern lv_obj_t *ui_Grill;
extern lv_obj_t *ui_Label12;
void ui_event_Light( lv_event_t * e);
extern lv_obj_t *ui_Light;
extern lv_obj_t *ui_Label13;
void ui_event_StopButton( lv_event_t * e);
extern lv_obj_t *ui_StopButton;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
