// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startProgram(lv_event_t * e);
void cancelProgram(lv_event_t * e);
void increaseHours(lv_event_t * e);
void decreaseHours(lv_event_t * e);
void increaseMinutes(lv_event_t * e);
void decreaseMinutes(lv_event_t * e);
void increaseTemperature(lv_event_t * e);
void decreaseTemperature(lv_event_t * e);
void toggleFan(lv_event_t * e);
void toggleGrill(lv_event_t * e);
void toggleLight(lv_event_t * e);
void stopProgram(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
