#pragma once

#if defined(_WIN64) || defined(_WIN32) || defined(__APPLE__) || defined(__linux__)

// EMULATION SETTINGS
#define EMULATION 1
#define EMU_BAKING_SECONDS_PER_MINUTE 5
#define EMU_HEATER_PER_SECOND_TEMP_INCREASE_PCT 0.2
#define EMU_HEATER_PER_SECOND_TEMP_DECREASE_PCT 0.2

#endif

// SETTINGS
#define BAKING_MAX_STEPS 3
#define BAKING_TEMPERATURE_MIN 30
#define BAKING_TEMPERATURE_MAX 300
#define BAKING_DURATION_M_MIN 1
#define BAKING_DURATION_M_MAX 60*10
#define HEATER_TEMPERATURE_COOL 25
#define HEATER_TEMPERATURE_INIT 20
