#pragma once

#if defined(_WIN64) || defined(_WIN32) || defined(__APPLE__) || defined(__linux__)

// EMULATION SETTINGS
#define EMULATION 1
#define EMU_BAKING_SECONDS_PER_MINUTE 5
#define EMU_TEMP_INC_PER_ON_CYCLE 0.1
#define EMU_TEMP_DECAY_PER_SECOND 0.2
#define EMU_TEMP_INIT 20
#define EMU_TEMP_COOL 25
#endif

// SETTINGS
#define DEBUG 1

#define OVEN_CONTROL_QUEUE_INTERVAL_MS 500
#define OVEN_STATE_HANDLE_INTERVAL_MS 200
#define OVEN_PROBE_SAMPLE_INTERVAL_MS 200
#define OVEN_ACTUATOR_HANDLE_INTERVAL_MS 200
#define OVEN_DEBUG_INTERVAL_MS 2000
#define OVEN_DATA_UPDATE_INTERVAL_MS 500

#define OVEN_PID_SAMPLE_TIME_MS 100
#define OVEN_CONTROL_WINDOW_SIZE_MS 2000

#define BAKING_MAX_STEPS 3
#define BAKING_TEMPERATURE_MIN 30
#define BAKING_TEMPERATURE_MAX 300
#define BAKING_DURATION_M_MIN 1
#define BAKING_DURATION_M_MAX 60 * 10

#define PRINT_DATA_INTERVAL_S 10

#define HAS_FAN 1
#define HAS_GRILL 0
#define HAS_DECK_PROBE 0

#define FAN_PIN 1
#define LIGHT_PIN 2
#define TOP_HEATER_PIN 3
#define GRILL_HEATER_PIN 4
#define DECK_HEATER_PIN 5
#define CHAMBER_PROBE_PIN 6
#define DECK_PROBE_PIN 7
