
// EMULATION SETTINGS
#define EMULATION 1
#define EMU_BAKING_SECONDS_PER_MINUTE 5
#define EMU_HEATER_ENV_TEMPERATURE 20
#define EMU_HEATER_PER_SECOND_TEMP_INCREASE_PCT 0.2
#define EMU_HEATER_PER_SECOND_TEMP_DECREASE_PCT 0.2
// SETTINGS
#define BAKING_TEMPERATURE_MIN 30
#define BAKING_TEMPERATURE_MAX 300
#define BAKING_DURATION_M_MIN 1
#define BAKING_DURATION_M_MAX 60*10
#define HEATER_TEMPERATURE_COOL 25
